### ISSUE TITLE
Level API does not load

### ISSUE THREAD

**Issue by HGStyle** [Cvolton/GDHistory#8] opened 2023-07-25 18:53 UTC
Here is the URL I tried:
https://history.geometrydash.eu/api/v1/level/128/brief
I opened it in my browser (Brave) but it does not load.
When requesting a level that never existed, it returns a weird result.
For example, for the API, ID 0 returns ReTraY:
https://history.geometrydash.eu/api/v1/level/0/brief/
Returns:
{"online_id": 0, "comment": "", "is_deleted": true, "cache_level_name": "ReTraY", "cache_submitted": "2018-04-22T00:00:00Z", "cache_submitted_timestamp": 1524355200, "cache_downloads": 20976497, "cache_likes": 3102391, "cache_rating_sum": 10, "cache_rating": 10, "cache_demon": false, "cache_auto": false, "cache_demon_type": 0, "cache_stars": 2, "cache_username": "DiMaViKuLov26", "cache_level_string_available": false, "cache_user_id": 4993756, "cache_daily_id": 0, "cache_needs_updating": true, "cache_available_versions": 0, "cache_search_available": false, "cache_main_difficulty": 1, "cache_max_stars": 5, "cache_filter_difficulty": 2, "cache_length": 3, "cache_featured": 7730, "cache_max_featured": 23802, "cache_epic": 0, "cache_max_epic": 1, "cache_two_player": false, "cache_max_two_player": false, "cache_original": 0, "cache_max_original": 0, "cache_needs_revalidation": false, "level_string_count": 0}
For the API, the level has been deleted since while we all know it's not...
Could you fix it please ?
Thanks you ! (for now I'll have to use `requests` and `bs4` to extract level data I think...)

**Comment by Cvolton** [comment] 2023-07-26 16:15
This is very likely caused by the amount of records 128 has, for which 128 is a very big edge case. Level 0 returns the same result on the actual website as well, so that is intended behavior (records for levels below 91 usually aren't manually cleared, as they are hidden from search)

The fundamental bug here is the same as #5 , except that issue is about the website itself

**Comment by Cvolton** [comment] 2023-07-29 19:23
updated so 128 loads, although it's still much slower than it should be

**Comment by HGStyle** [comment] 2023-08-20 17:09
Thanks you, I'll see if I use the API or I scrape the data using BS4. (I
have allready started coding using BS4 but it'll not be hard to use the API
instead)

**Comment by Cvolton** [comment] 2024-03-22 00:39
more or less addressed in 7b03c893357e91b6a8917bf8d84b2705837e26fc

**Closed as completed by Cvolton** 2024-03-22 00:39 UTC
